export function formatHeroName(heroName) {
  return heroName.replace('_', ' ').replace(/([A-Z])/g, ' $1').slice(1)
}

const capitalize = (str) =>
  str.replace(/(?:^|\s|["'([{])+\S/g, match => match.toUpperCase());

export function formatName(name) {
  return capitalize(name
    .replace('npc_dota_hero_', '')
    .replace('item_', '')
    .replace(/_/g, ' '))
}

export function isEmpty(obj) {
  return !obj || Object.keys(obj).length === 0
}

export function compareTime(first, second) {
  let firstTokens = first.split(':').map((t) => parseInt(t))
  let secondTokens = second.split(':').map((t) => parseInt(t))

  if (firstTokens[0] === secondTokens[0]) {
    return firstTokens[1] - secondTokens[1]
  }

  return firstTokens[0] - secondTokens[0]
}

export function getItemClassName(name) {
  return name.toLowerCase().replace(' ', '-')
}

export const DotaHeroes = JSON.parse(`{
  "result":{
  "heroes":[
  {
  "name":"npc_dota_hero_antimage",
  "id":1
  },
  {
  "name":"npc_dota_hero_axe",
  "id":2
  },
  {
  "name":"npc_dota_hero_bane",
  "id":3
  },
  {
  "name":"npc_dota_hero_bloodseeker",
  "id":4
  },
  {
  "name":"npc_dota_hero_crystal_maiden",
  "id":5
  },
  {
  "name":"npc_dota_hero_drow_ranger",
  "id":6
  },
  {
  "name":"npc_dota_hero_earthshaker",
  "id":7
  },
  {
  "name":"npc_dota_hero_juggernaut",
  "id":8
  },
  {
  "name":"npc_dota_hero_mirana",
  "id":9
  },
  {
  "name":"npc_dota_hero_nevermore",
  "id":11
  },
  {
  "name":"npc_dota_hero_morphling",
  "id":10
  },
  {
  "name":"npc_dota_hero_phantom_lancer",
  "id":12
  },
  {
  "name":"npc_dota_hero_puck",
  "id":13
  },
  {
  "name":"npc_dota_hero_pudge",
  "id":14
  },
  {
  "name":"npc_dota_hero_razor",
  "id":15
  },
  {
  "name":"npc_dota_hero_sand_king",
  "id":16
  },
  {
  "name":"npc_dota_hero_storm_spirit",
  "id":17
  },
  {
  "name":"npc_dota_hero_sven",
  "id":18
  },
  {
  "name":"npc_dota_hero_tiny",
  "id":19
  },
  {
  "name":"npc_dota_hero_vengefulspirit",
  "id":20
  },
  {
  "name":"npc_dota_hero_windrunner",
  "id":21
  },
  {
  "name":"npc_dota_hero_zuus",
  "id":22
  },
  {
  "name":"npc_dota_hero_kunkka",
  "id":23
  },
  {
  "name":"npc_dota_hero_lina",
  "id":25
  },
  {
  "name":"npc_dota_hero_lich",
  "id":31
  },
  {
  "name":"npc_dota_hero_lion",
  "id":26
  },
  {
  "name":"npc_dota_hero_shadow_shaman",
  "id":27
  },
  {
  "name":"npc_dota_hero_slardar",
  "id":28
  },
  {
  "name":"npc_dota_hero_tidehunter",
  "id":29
  },
  {
  "name":"npc_dota_hero_witch_doctor",
  "id":30
  },
  {
  "name":"npc_dota_hero_riki",
  "id":32
  },
  {
  "name":"npc_dota_hero_enigma",
  "id":33
  },
  {
  "name":"npc_dota_hero_tinker",
  "id":34
  },
  {
  "name":"npc_dota_hero_sniper",
  "id":35
  },
  {
  "name":"npc_dota_hero_necrolyte",
  "id":36
  },
  {
  "name":"npc_dota_hero_warlock",
  "id":37
  },
  {
  "name":"npc_dota_hero_beastmaster",
  "id":38
  },
  {
  "name":"npc_dota_hero_queenofpain",
  "id":39
  },
  {
  "name":"npc_dota_hero_venomancer",
  "id":40
  },
  {
  "name":"npc_dota_hero_faceless_void",
  "id":41
  },
  {
  "name":"npc_dota_hero_skeleton_king",
  "id":42
  },
  {
  "name":"npc_dota_hero_death_prophet",
  "id":43
  },
  {
  "name":"npc_dota_hero_phantom_assassin",
  "id":44
  },
  {
  "name":"npc_dota_hero_pugna",
  "id":45
  },
  {
  "name":"npc_dota_hero_templar_assassin",
  "id":46
  },
  {
  "name":"npc_dota_hero_viper",
  "id":47
  },
  {
  "name":"npc_dota_hero_luna",
  "id":48
  },
  {
  "name":"npc_dota_hero_dragon_knight",
  "id":49
  },
  {
  "name":"npc_dota_hero_dazzle",
  "id":50
  },
  {
  "name":"npc_dota_hero_rattletrap",
  "id":51
  },
  {
  "name":"npc_dota_hero_leshrac",
  "id":52
  },
  {
  "name":"npc_dota_hero_furion",
  "id":53
  },
  {
  "name":"npc_dota_hero_life_stealer",
  "id":54
  },
  {
  "name":"npc_dota_hero_dark_seer",
  "id":55
  },
  {
  "name":"npc_dota_hero_clinkz",
  "id":56
  },
  {
  "name":"npc_dota_hero_omniknight",
  "id":57
  },
  {
  "name":"npc_dota_hero_enchantress",
  "id":58
  },
  {
  "name":"npc_dota_hero_huskar",
  "id":59
  },
  {
  "name":"npc_dota_hero_night_stalker",
  "id":60
  },
  {
  "name":"npc_dota_hero_broodmother",
  "id":61
  },
  {
  "name":"npc_dota_hero_bounty_hunter",
  "id":62
  },
  {
  "name":"npc_dota_hero_weaver",
  "id":63
  },
  {
  "name":"npc_dota_hero_jakiro",
  "id":64
  },
  {
  "name":"npc_dota_hero_batrider",
  "id":65
  },
  {
  "name":"npc_dota_hero_chen",
  "id":66
  },
  {
  "name":"npc_dota_hero_spectre",
  "id":67
  },
  {
  "name":"npc_dota_hero_doom_bringer",
  "id":69
  },
  {
  "name":"npc_dota_hero_ancient_apparition",
  "id":68
  },
  {
  "name":"npc_dota_hero_ursa",
  "id":70
  },
  {
  "name":"npc_dota_hero_spirit_breaker",
  "id":71
  },
  {
  "name":"npc_dota_hero_gyrocopter",
  "id":72
  },
  {
  "name":"npc_dota_hero_alchemist",
  "id":73
  },
  {
  "name":"npc_dota_hero_invoker",
  "id":74
  },
  {
  "name":"npc_dota_hero_silencer",
  "id":75
  },
  {
  "name":"npc_dota_hero_obsidian_destroyer",
  "id":76
  },
  {
  "name":"npc_dota_hero_lycan",
  "id":77
  },
  {
  "name":"npc_dota_hero_brewmaster",
  "id":78
  },
  {
  "name":"npc_dota_hero_shadow_demon",
  "id":79
  },
  {
  "name":"npc_dota_hero_lone_druid",
  "id":80
  },
  {
  "name":"npc_dota_hero_chaos_knight",
  "id":81
  },
  {
  "name":"npc_dota_hero_meepo",
  "id":82
  },
  {
  "name":"npc_dota_hero_treant",
  "id":83
  },
  {
  "name":"npc_dota_hero_ogre_magi",
  "id":84
  },
  {
  "name":"npc_dota_hero_undying",
  "id":85
  },
  {
  "name":"npc_dota_hero_rubick",
  "id":86
  },
  {
  "name":"npc_dota_hero_disruptor",
  "id":87
  },
  {
  "name":"npc_dota_hero_nyx_assassin",
  "id":88
  },
  {
  "name":"npc_dota_hero_naga_siren",
  "id":89
  },
  {
  "name":"npc_dota_hero_keeper_of_the_light",
  "id":90
  },
  {
  "name":"npc_dota_hero_wisp",
  "id":91
  },
  {
  "name":"npc_dota_hero_visage",
  "id":92
  },
  {
  "name":"npc_dota_hero_slark",
  "id":93
  },
  {
  "name":"npc_dota_hero_medusa",
  "id":94
  },
  {
  "name":"npc_dota_hero_troll_warlord",
  "id":95
  },
  {
  "name":"npc_dota_hero_centaur",
  "id":96
  },
  {
  "name":"npc_dota_hero_magnataur",
  "id":97
  },
  {
  "name":"npc_dota_hero_shredder",
  "id":98
  },
  {
  "name":"npc_dota_hero_bristleback",
  "id":99
  },
  {
  "name":"npc_dota_hero_tusk",
  "id":100
  },
  {
  "name":"npc_dota_hero_skywrath_mage",
  "id":101
  },
  {
  "name":"npc_dota_hero_abaddon",
  "id":102
  },
  {
  "name":"npc_dota_hero_elder_titan",
  "id":103
  },
  {
  "name":"npc_dota_hero_legion_commander",
  "id":104
  },
  {
  "name":"npc_dota_hero_ember_spirit",
  "id":106
  },
  {
  "name":"npc_dota_hero_earth_spirit",
  "id":107
  },
  {
  "name":"npc_dota_hero_terrorblade",
  "id":109
  },
  {
  "name":"npc_dota_hero_phoenix",
  "id":110
  },
  {
  "name":"npc_dota_hero_oracle",
  "id":111
  },
  {
  "name":"npc_dota_hero_techies",
  "id":105
  },
  {
  "name":"npc_dota_hero_winter_wyvern",
  "id":112
  },
  {
  "name":"npc_dota_hero_arc_warden",
  "id":113
  },
  {
  "name":"npc_dota_hero_abyssal_underlord",
  "id":108
  },
  {
  "name":"npc_dota_hero_monkey_king",
  "id":114
  },
  {
  "name":"npc_dota_hero_pangolier",
  "id":120
  },
  {
  "name":"npc_dota_hero_dark_willow",
  "id":119
  },
  {
  "name":"npc_dota_hero_grimstroke",
  "id":121
  },
  {
  "name":"npc_dota_hero_mars",
  "id":129
  },
  {
  "name":"npc_dota_hero_void_spirit",
  "id":126
  },
  {
  "name":"npc_dota_hero_snapfire",
  "id":128
  },
  {
  "name":"npc_dota_hero_hoodwink",
  "id":123
  },
  {
  "name":"npc_dota_hero_dawnbreaker",
  "id":135
  },
  {
  "name":"npc_dota_hero_marci",
  "id":136
  }
  ]
  ,
  "status":200,
  "count":122
  }
  }`).result.heroes

export const DotaItems = JSON.parse(`{
  "result":{
  "items":[
  {
  "id":1,
  "name":"item_blink",
  "cost":2250,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":600,
  "name":"item_overwhelming_blink",
  "cost":6800,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":603,
  "name":"item_swift_blink",
  "cost":6800,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":604,
  "name":"item_arcane_blink",
  "cost":6800,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":606,
  "name":"item_recipe_arcane_blink",
  "cost":1750,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":607,
  "name":"item_recipe_swift_blink",
  "cost":1750,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":608,
  "name":"item_recipe_overwhelming_blink",
  "cost":1750,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":2,
  "name":"item_blades_of_attack",
  "cost":450,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":3,
  "name":"item_broadsword",
  "cost":1000,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":4,
  "name":"item_chainmail",
  "cost":550,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":5,
  "name":"item_claymore",
  "cost":1350,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":6,
  "name":"item_helm_of_iron_will",
  "cost":975,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":7,
  "name":"item_javelin",
  "cost":1100,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":8,
  "name":"item_mithril_hammer",
  "cost":1600,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":9,
  "name":"item_platemail",
  "cost":1400,
  "secret_shop":1,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":10,
  "name":"item_quarterstaff",
  "cost":875,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":11,
  "name":"item_quelling_blade",
  "cost":130,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":237,
  "name":"item_faerie_fire",
  "cost":70,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":265,
  "name":"item_infused_raindrop",
  "cost":225,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":244,
  "name":"item_wind_lace",
  "cost":250,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":12,
  "name":"item_ring_of_protection",
  "cost":175,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":182,
  "name":"item_stout_shield",
  "cost":100,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":246,
  "name":"item_recipe_moon_shard",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":247,
  "name":"item_moon_shard",
  "cost":4000,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":13,
  "name":"item_gauntlets",
  "cost":140,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":14,
  "name":"item_slippers",
  "cost":140,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":15,
  "name":"item_mantle",
  "cost":140,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":16,
  "name":"item_branches",
  "cost":50,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":17,
  "name":"item_belt_of_strength",
  "cost":450,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":18,
  "name":"item_boots_of_elves",
  "cost":450,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":19,
  "name":"item_robe",
  "cost":450,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":20,
  "name":"item_circlet",
  "cost":155,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":261,
  "name":"item_crown",
  "cost":450,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":21,
  "name":"item_ogre_axe",
  "cost":1000,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":22,
  "name":"item_blade_of_alacrity",
  "cost":1000,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":23,
  "name":"item_staff_of_wizardry",
  "cost":1000,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":24,
  "name":"item_ultimate_orb",
  "cost":2050,
  "secret_shop":1,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":25,
  "name":"item_gloves",
  "cost":450,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":485,
  "name":"item_blitz_knuckles",
  "cost":1000,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":26,
  "name":"item_lifesteal",
  "cost":900,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":473,
  "name":"item_voodoo_mask",
  "cost":700,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":27,
  "name":"item_ring_of_regen",
  "cost":175,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":279,
  "name":"item_ring_of_tarrasque",
  "cost":650,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":28,
  "name":"item_sobi_mask",
  "cost":175,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":29,
  "name":"item_boots",
  "cost":500,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":30,
  "name":"item_gem",
  "cost":900,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":31,
  "name":"item_cloak",
  "cost":500,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":32,
  "name":"item_talisman_of_evasion",
  "cost":1300,
  "secret_shop":1,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":33,
  "name":"item_cheese",
  "cost":1000,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":34,
  "name":"item_magic_stick",
  "cost":200,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":35,
  "name":"item_recipe_magic_wand",
  "cost":150,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":36,
  "name":"item_magic_wand",
  "cost":450,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":37,
  "name":"item_ghost",
  "cost":1500,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":38,
  "name":"item_clarity",
  "cost":50,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":216,
  "name":"item_enchanted_mango",
  "cost":65,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":39,
  "name":"item_flask",
  "cost":110,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":40,
  "name":"item_dust",
  "cost":80,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":41,
  "name":"item_bottle",
  "cost":675,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":42,
  "name":"item_ward_observer",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":43,
  "name":"item_ward_sentry",
  "cost":50,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":217,
  "name":"item_recipe_ward_dispenser",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":218,
  "name":"item_ward_dispenser",
  "cost":50,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":44,
  "name":"item_tango",
  "cost":90,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":241,
  "name":"item_tango_single",
  "cost":30,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":45,
  "name":"item_courier",
  "cost":50,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":286,
  "name":"item_flying_courier",
  "cost":100,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":46,
  "name":"item_tpscroll",
  "cost":100,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":47,
  "name":"item_recipe_travel_boots",
  "cost":2000,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":219,
  "name":"item_recipe_travel_boots_2",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":48,
  "name":"item_travel_boots",
  "cost":2500,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":220,
  "name":"item_travel_boots_2",
  "cost":4500,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":49,
  "name":"item_recipe_phase_boots",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":50,
  "name":"item_phase_boots",
  "cost":1500,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":51,
  "name":"item_demon_edge",
  "cost":2200,
  "secret_shop":1,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":52,
  "name":"item_eagle",
  "cost":2800,
  "secret_shop":1,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":53,
  "name":"item_reaver",
  "cost":2800,
  "secret_shop":1,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":54,
  "name":"item_relic",
  "cost":3750,
  "secret_shop":1,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":55,
  "name":"item_hyperstone",
  "cost":2000,
  "secret_shop":1,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":56,
  "name":"item_ring_of_health",
  "cost":825,
  "secret_shop":1,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":57,
  "name":"item_void_stone",
  "cost":825,
  "secret_shop":1,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":58,
  "name":"item_mystic_staff",
  "cost":2800,
  "secret_shop":1,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":59,
  "name":"item_energy_booster",
  "cost":800,
  "secret_shop":1,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":60,
  "name":"item_point_booster",
  "cost":1200,
  "secret_shop":1,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":61,
  "name":"item_vitality_booster",
  "cost":1000,
  "secret_shop":1,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":593,
  "name":"item_fluffy_hat",
  "cost":250,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":62,
  "name":"item_recipe_power_treads",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":63,
  "name":"item_power_treads",
  "cost":1400,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":653,
  "name":"item_recipe_grandmasters_glaive",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":655,
  "name":"item_grandmasters_glaive",
  "cost":5000,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":64,
  "name":"item_recipe_hand_of_midas",
  "cost":1750,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":65,
  "name":"item_hand_of_midas",
  "cost":2200,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":66,
  "name":"item_recipe_oblivion_staff",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":67,
  "name":"item_oblivion_staff",
  "cost":1500,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":533,
  "name":"item_recipe_witch_blade",
  "cost":600,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":534,
  "name":"item_witch_blade",
  "cost":2600,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":68,
  "name":"item_recipe_pers",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":69,
  "name":"item_pers",
  "cost":1650,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":70,
  "name":"item_recipe_poor_mans_shield",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":71,
  "name":"item_poor_mans_shield",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":731,
  "name":"item_satchel",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":72,
  "name":"item_recipe_bracer",
  "cost":210,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":73,
  "name":"item_bracer",
  "cost":505,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":74,
  "name":"item_recipe_wraith_band",
  "cost":210,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":75,
  "name":"item_wraith_band",
  "cost":505,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":76,
  "name":"item_recipe_null_talisman",
  "cost":210,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":77,
  "name":"item_null_talisman",
  "cost":505,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":78,
  "name":"item_recipe_mekansm",
  "cost":900,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":79,
  "name":"item_mekansm",
  "cost":1875,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":80,
  "name":"item_recipe_vladmir",
  "cost":400,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":81,
  "name":"item_vladmir",
  "cost":2600,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":85,
  "name":"item_recipe_buckler",
  "cost":250,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":86,
  "name":"item_buckler",
  "cost":425,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":87,
  "name":"item_recipe_ring_of_basilius",
  "cost":250,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":88,
  "name":"item_ring_of_basilius",
  "cost":425,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":268,
  "name":"item_recipe_holy_locket",
  "cost":475,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":269,
  "name":"item_holy_locket",
  "cost":2400,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":89,
  "name":"item_recipe_pipe",
  "cost":1550,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":90,
  "name":"item_pipe",
  "cost":3475,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":91,
  "name":"item_recipe_urn_of_shadows",
  "cost":335,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":92,
  "name":"item_urn_of_shadows",
  "cost":840,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":93,
  "name":"item_recipe_headdress",
  "cost":250,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":94,
  "name":"item_headdress",
  "cost":425,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":95,
  "name":"item_recipe_sheepstick",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":96,
  "name":"item_sheepstick",
  "cost":5675,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":97,
  "name":"item_recipe_orchid",
  "cost":475,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":98,
  "name":"item_orchid",
  "cost":3475,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":245,
  "name":"item_recipe_bloodthorn",
  "cost":800,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":250,
  "name":"item_bloodthorn",
  "cost":6275,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":251,
  "name":"item_recipe_echo_sabre",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":252,
  "name":"item_echo_sabre",
  "cost":2500,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":99,
  "name":"item_recipe_cyclone",
  "cost":650,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":100,
  "name":"item_cyclone",
  "cost":2725,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":612,
  "name":"item_recipe_wind_waker",
  "cost":1300,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":610,
  "name":"item_wind_waker",
  "cost":6825,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":233,
  "name":"item_recipe_aether_lens",
  "cost":650,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":232,
  "name":"item_aether_lens",
  "cost":2275,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":101,
  "name":"item_recipe_force_staff",
  "cost":950,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":102,
  "name":"item_force_staff",
  "cost":2200,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":262,
  "name":"item_recipe_hurricane_pike",
  "cost":350,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":263,
  "name":"item_hurricane_pike",
  "cost":4450,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":103,
  "name":"item_recipe_dagon",
  "cost":1250,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":197,
  "name":"item_recipe_dagon_2",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":198,
  "name":"item_recipe_dagon_3",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":199,
  "name":"item_recipe_dagon_4",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":200,
  "name":"item_recipe_dagon_5",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":104,
  "name":"item_dagon",
  "cost":2700,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":201,
  "name":"item_dagon_2",
  "cost":3950,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":202,
  "name":"item_dagon_3",
  "cost":5200,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":203,
  "name":"item_dagon_4",
  "cost":6450,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":204,
  "name":"item_dagon_5",
  "cost":7700,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":105,
  "name":"item_recipe_necronomicon",
  "cost":1250,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":191,
  "name":"item_recipe_necronomicon_2",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":192,
  "name":"item_recipe_necronomicon_3",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":106,
  "name":"item_necronomicon",
  "cost":2050,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":193,
  "name":"item_necronomicon_2",
  "cost":3300,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":194,
  "name":"item_necronomicon_3",
  "cost":4550,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":107,
  "name":"item_recipe_ultimate_scepter",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":108,
  "name":"item_ultimate_scepter",
  "cost":4200,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":270,
  "name":"item_recipe_ultimate_scepter_2",
  "cost":1600,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":271,
  "name":"item_ultimate_scepter_2",
  "cost":5800,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":727,
  "name":"item_ultimate_scepter_roshan",
  "cost":5800,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":609,
  "name":"item_aghanims_shard",
  "cost":1400,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":725,
  "name":"item_aghanims_shard_roshan",
  "cost":1400,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":109,
  "name":"item_recipe_refresher",
  "cost":1700,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":110,
  "name":"item_refresher",
  "cost":5000,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":111,
  "name":"item_recipe_assault",
  "cost":1300,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":112,
  "name":"item_assault",
  "cost":5125,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":113,
  "name":"item_recipe_heart",
  "cost":1200,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":114,
  "name":"item_heart",
  "cost":5000,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":115,
  "name":"item_recipe_black_king_bar",
  "cost":1450,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":116,
  "name":"item_black_king_bar",
  "cost":4050,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":117,
  "name":"item_aegis",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":118,
  "name":"item_recipe_shivas_guard",
  "cost":650,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":119,
  "name":"item_shivas_guard",
  "cost":4850,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":120,
  "name":"item_recipe_bloodstone",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":121,
  "name":"item_bloodstone",
  "cost":5750,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":122,
  "name":"item_recipe_sphere",
  "cost":900,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":123,
  "name":"item_sphere",
  "cost":4600,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":221,
  "name":"item_recipe_lotus_orb",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":226,
  "name":"item_lotus_orb",
  "cost":3850,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":222,
  "name":"item_recipe_meteor_hammer",
  "cost":250,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":223,
  "name":"item_meteor_hammer",
  "cost":2350,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":224,
  "name":"item_recipe_nullifier",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":225,
  "name":"item_nullifier",
  "cost":4725,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":255,
  "name":"item_recipe_aeon_disk",
  "cost":1200,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":256,
  "name":"item_aeon_disk",
  "cost":3000,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":258,
  "name":"item_recipe_kaya",
  "cost":600,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":259,
  "name":"item_kaya",
  "cost":2050,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":369,
  "name":"item_trident",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":276,
  "name":"item_combo_breaker",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":260,
  "name":"item_refresher_shard",
  "cost":1000,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":266,
  "name":"item_recipe_spirit_vessel",
  "cost":1000,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":267,
  "name":"item_spirit_vessel",
  "cost":2840,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":124,
  "name":"item_recipe_vanguard",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":125,
  "name":"item_vanguard",
  "cost":1825,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":243,
  "name":"item_recipe_crimson_guard",
  "cost":800,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":242,
  "name":"item_crimson_guard",
  "cost":3600,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":126,
  "name":"item_recipe_blade_mail",
  "cost":575,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":127,
  "name":"item_blade_mail",
  "cost":2125,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":128,
  "name":"item_recipe_soul_booster",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":129,
  "name":"item_soul_booster",
  "cost":3000,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":130,
  "name":"item_recipe_hood_of_defiance",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":131,
  "name":"item_hood_of_defiance",
  "cost":1500,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":691,
  "name":"item_recipe_eternal_shroud",
  "cost":1100,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":692,
  "name":"item_eternal_shroud",
  "cost":3300,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":132,
  "name":"item_recipe_rapier",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":133,
  "name":"item_rapier",
  "cost":5950,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":134,
  "name":"item_recipe_monkey_king_bar",
  "cost":675,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":135,
  "name":"item_monkey_king_bar",
  "cost":4975,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":136,
  "name":"item_recipe_radiance",
  "cost":1350,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":137,
  "name":"item_radiance",
  "cost":5100,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":138,
  "name":"item_recipe_butterfly",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":139,
  "name":"item_butterfly",
  "cost":4975,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":140,
  "name":"item_recipe_greater_crit",
  "cost":1000,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":141,
  "name":"item_greater_crit",
  "cost":5150,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":142,
  "name":"item_recipe_basher",
  "cost":825,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":143,
  "name":"item_basher",
  "cost":2875,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":144,
  "name":"item_recipe_bfury",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":145,
  "name":"item_bfury",
  "cost":4130,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":146,
  "name":"item_recipe_manta",
  "cost":500,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":147,
  "name":"item_manta",
  "cost":4600,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":148,
  "name":"item_recipe_lesser_crit",
  "cost":500,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":149,
  "name":"item_lesser_crit",
  "cost":1950,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":234,
  "name":"item_recipe_dragon_lance",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":236,
  "name":"item_dragon_lance",
  "cost":1900,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":150,
  "name":"item_recipe_armlet",
  "cost":625,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":151,
  "name":"item_armlet",
  "cost":2500,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":183,
  "name":"item_recipe_invis_sword",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":152,
  "name":"item_invis_sword",
  "cost":3000,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":248,
  "name":"item_recipe_silver_edge",
  "cost":500,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":249,
  "name":"item_silver_edge",
  "cost":5450,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":153,
  "name":"item_recipe_sange_and_yasha",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":154,
  "name":"item_sange_and_yasha",
  "cost":4100,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":272,
  "name":"item_recipe_kaya_and_sange",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":273,
  "name":"item_kaya_and_sange",
  "cost":4100,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":274,
  "name":"item_recipe_yasha_and_kaya",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":277,
  "name":"item_yasha_and_kaya",
  "cost":4100,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":155,
  "name":"item_recipe_satanic",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":156,
  "name":"item_satanic",
  "cost":5050,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":157,
  "name":"item_recipe_mjollnir",
  "cost":900,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":158,
  "name":"item_mjollnir",
  "cost":5600,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":159,
  "name":"item_recipe_skadi",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":160,
  "name":"item_skadi",
  "cost":5300,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":161,
  "name":"item_recipe_sange",
  "cost":600,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":162,
  "name":"item_sange",
  "cost":2050,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":163,
  "name":"item_recipe_helm_of_the_dominator",
  "cost":975,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":164,
  "name":"item_helm_of_the_dominator",
  "cost":2400,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":633,
  "name":"item_recipe_helm_of_the_overlord",
  "cost":1325,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":635,
  "name":"item_helm_of_the_overlord",
  "cost":6325,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":165,
  "name":"item_recipe_maelstrom",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":166,
  "name":"item_maelstrom",
  "cost":2700,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":1565,
  "name":"item_recipe_gungir",
  "cost":700,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":1466,
  "name":"item_gungir",
  "cost":6150,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":167,
  "name":"item_recipe_desolator",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":168,
  "name":"item_desolator",
  "cost":3500,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":169,
  "name":"item_recipe_yasha",
  "cost":600,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":170,
  "name":"item_yasha",
  "cost":2050,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":171,
  "name":"item_recipe_mask_of_madness",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":172,
  "name":"item_mask_of_madness",
  "cost":1775,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":173,
  "name":"item_recipe_diffusal_blade",
  "cost":700,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":174,
  "name":"item_diffusal_blade",
  "cost":3150,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":175,
  "name":"item_recipe_ethereal_blade",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":176,
  "name":"item_ethereal_blade",
  "cost":4300,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":177,
  "name":"item_recipe_soul_ring",
  "cost":225,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":178,
  "name":"item_soul_ring",
  "cost":680,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":179,
  "name":"item_recipe_arcane_boots",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":180,
  "name":"item_arcane_boots",
  "cost":1300,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":228,
  "name":"item_recipe_octarine_core",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":235,
  "name":"item_octarine_core",
  "cost":5275,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":181,
  "name":"item_orb_of_venom",
  "cost":275,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":240,
  "name":"item_blight_stone",
  "cost":300,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":640,
  "name":"item_recipe_orb_of_corrosion",
  "cost":100,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":569,
  "name":"item_orb_of_corrosion",
  "cost":925,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":599,
  "name":"item_recipe_falcon_blade",
  "cost":250,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":596,
  "name":"item_falcon_blade",
  "cost":1125,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":597,
  "name":"item_recipe_mage_slayer",
  "cost":400,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":598,
  "name":"item_mage_slayer",
  "cost":2400,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":184,
  "name":"item_recipe_ancient_janggo",
  "cost":550,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":185,
  "name":"item_ancient_janggo",
  "cost":1700,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":186,
  "name":"item_recipe_medallion_of_courage",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":187,
  "name":"item_medallion_of_courage",
  "cost":1025,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":227,
  "name":"item_recipe_solar_crest",
  "cost":900,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":229,
  "name":"item_solar_crest",
  "cost":2625,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":188,
  "name":"item_smoke_of_deceit",
  "cost":50,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":257,
  "name":"item_tome_of_knowledge",
  "cost":75,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":189,
  "name":"item_recipe_veil_of_discord",
  "cost":650,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":190,
  "name":"item_veil_of_discord",
  "cost":1525,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":230,
  "name":"item_recipe_guardian_greaves",
  "cost":1500,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":231,
  "name":"item_guardian_greaves",
  "cost":5100,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":205,
  "name":"item_recipe_rod_of_atos",
  "cost":850,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":206,
  "name":"item_rod_of_atos",
  "cost":2750,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":238,
  "name":"item_recipe_iron_talon",
  "cost":1,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":239,
  "name":"item_iron_talon",
  "cost":301,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":207,
  "name":"item_recipe_abyssal_blade",
  "cost":1550,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":208,
  "name":"item_abyssal_blade",
  "cost":6250,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":209,
  "name":"item_recipe_heavens_halberd",
  "cost":200,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":210,
  "name":"item_heavens_halberd",
  "cost":3550,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":211,
  "name":"item_recipe_ring_of_aquila",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":212,
  "name":"item_ring_of_aquila",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":213,
  "name":"item_recipe_tranquil_boots",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":214,
  "name":"item_tranquil_boots",
  "cost":925,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":215,
  "name":"item_shadow_amulet",
  "cost":1000,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":253,
  "name":"item_recipe_glimmer_cape",
  "cost":450,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":254,
  "name":"item_glimmer_cape",
  "cost":1950,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":1021,
  "name":"item_river_painter",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":1022,
  "name":"item_river_painter2",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":1023,
  "name":"item_river_painter3",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":1024,
  "name":"item_river_painter4",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":1025,
  "name":"item_river_painter5",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":1026,
  "name":"item_river_painter6",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":1027,
  "name":"item_river_painter7",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":1028,
  "name":"item_mutation_tombstone",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":1029,
  "name":"item_super_blink",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":1030,
  "name":"item_pocket_tower",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":1032,
  "name":"item_pocket_roshan",
  "cost":1000,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":287,
  "name":"item_keen_optic",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":288,
  "name":"item_grove_bow",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":289,
  "name":"item_quickening_charm",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":290,
  "name":"item_philosophers_stone",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":291,
  "name":"item_force_boots",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":292,
  "name":"item_desolator_2",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":293,
  "name":"item_phoenix_ash",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":294,
  "name":"item_seer_stone",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":295,
  "name":"item_greater_mango",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":302,
  "name":"item_elixer",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":297,
  "name":"item_vampire_fangs",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":829,
  "name":"item_force_field",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":833,
  "name":"item_tree_processor",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":834,
  "name":"item_black_powder_bag",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":849,
  "name":"item_mechanical_arm",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":298,
  "name":"item_craggy_coat",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":299,
  "name":"item_greater_faerie_fire",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":300,
  "name":"item_timeless_relic",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":301,
  "name":"item_mirror_shield",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":303,
  "name":"item_recipe_ironwood_tree",
  "cost":1,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":304,
  "name":"item_ironwood_tree",
  "cost":151,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":328,
  "name":"item_mango_tree",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":305,
  "name":"item_royal_jelly",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":306,
  "name":"item_pupils_gift",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":307,
  "name":"item_tome_of_aghanim",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":308,
  "name":"item_repair_kit",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":309,
  "name":"item_mind_breaker",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":310,
  "name":"item_third_eye",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":311,
  "name":"item_spell_prism",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":325,
  "name":"item_princes_knife",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":330,
  "name":"item_witless_shako",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":334,
  "name":"item_imp_claw",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":335,
  "name":"item_flicker",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":336,
  "name":"item_spy_gadget",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":326,
  "name":"item_spider_legs",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":327,
  "name":"item_helm_of_the_undying",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":329,
  "name":"item_recipe_vambrace",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":331,
  "name":"item_vambrace",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":312,
  "name":"item_horizon",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":313,
  "name":"item_fusion_rune",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":354,
  "name":"item_ocean_heart",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":355,
  "name":"item_broom_handle",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":356,
  "name":"item_trusty_shovel",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":357,
  "name":"item_nether_shawl",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":358,
  "name":"item_dragon_scale",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":359,
  "name":"item_essence_ring",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":360,
  "name":"item_clumsy_net",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":361,
  "name":"item_enchanted_quiver",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":362,
  "name":"item_ninja_gear",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":363,
  "name":"item_illusionsts_cape",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":364,
  "name":"item_havoc_hammer",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":365,
  "name":"item_panic_button",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":366,
  "name":"item_apex",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":367,
  "name":"item_ballista",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":368,
  "name":"item_woodland_striders",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":275,
  "name":"item_recipe_trident",
  "cost":1,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":370,
  "name":"item_demonicon",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":317,
  "name":"item_recipe_fallen_sky",
  "cost":1,
  "secret_shop":0,
  "side_shop":0,
  "recipe":1
  },
  {
  "id":371,
  "name":"item_fallen_sky",
  "cost":4751,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":372,
  "name":"item_pirate_hat",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":373,
  "name":"item_dimensional_doorway",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":374,
  "name":"item_ex_machina",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":375,
  "name":"item_faded_broach",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":376,
  "name":"item_paladin_sword",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":377,
  "name":"item_minotaur_horn",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":378,
  "name":"item_orb_of_destruction",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":379,
  "name":"item_the_leveller",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":349,
  "name":"item_arcane_ring",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":381,
  "name":"item_titan_sliver",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":565,
  "name":"item_chipped_vest",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":566,
  "name":"item_wizard_glass",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":570,
  "name":"item_gloves_of_travel",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":573,
  "name":"item_elven_tunic",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":574,
  "name":"item_cloak_of_flames",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":575,
  "name":"item_venom_gland",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":571,
  "name":"item_trickster_cloak",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":576,
  "name":"item_gladiator_helm",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":577,
  "name":"item_possessed_mask",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":578,
  "name":"item_ancient_perseverance",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":637,
  "name":"item_star_mace",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":638,
  "name":"item_penta_edged_sword",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":582,
  "name":"item_oakheart",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":674,
  "name":"item_warhammer",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":680,
  "name":"item_bullwhip",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":675,
  "name":"item_psychic_headband",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":676,
  "name":"item_ceremonial_robe",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":686,
  "name":"item_quicksilver_amulet",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":677,
  "name":"item_book_of_shadows",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":678,
  "name":"item_giants_ring",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":679,
  "name":"item_vengeances_shadow",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":585,
  "name":"item_stormcrafter",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":588,
  "name":"item_overflowing_elixir",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":589,
  "name":"item_mysterious_hat",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":824,
  "name":"item_assassins_dagger",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":825,
  "name":"item_ascetic_cap",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":826,
  "name":"item_sample_picker",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":827,
  "name":"item_icarus_wings",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":828,
  "name":"item_misericorde",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":836,
  "name":"item_light_robes",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":837,
  "name":"item_heavy_blade",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":838,
  "name":"item_unstable_wand",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":839,
  "name":"item_fortitude_ring",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":840,
  "name":"item_pogo_stick",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  },
  {
  "id":835,
  "name":"item_paintball",
  "cost":0,
  "secret_shop":0,
  "side_shop":0,
  "recipe":0
  }
  ]
  ,
  "status":200
  }
  }`).result.items