// Generated by ScalaTS 0.5.10: https://scala-ts.github.io/scala-ts/

import { AbilityId } from './AbilityId';
import { DamageAmount } from './DamageAmount';

export interface AbilityDamage {
  abilityId: AbilityId;
  damage: DamageAmount;
}