// Generated by ScalaTS 0.5.10: https://scala-ts.github.io/scala-ts/

import { BadSmokeFight } from './BadSmokeFight';
import { CourierState } from './CourierState';
import { MidasEfficiency } from './MidasEfficiency';
import { NotTankedCreepwave } from './NotTankedCreepwave';
import { ObserverOnVision } from './ObserverOnVision';
import { BadFight } from './BadFight';
import { OverlappedStun } from './OverlappedStun';
import { SmokeOnVision } from './SmokeOnVision';
import { SummonGoldFed } from './SummonGoldFed';
import { UnusedAbility } from './UnusedAbility';
import { UnusedItem } from './UnusedItem';
import { WorthlessGlyph } from './WorthlessGlyph';
import { LostFightsUnderTheSameWard } from "./LostFightsUnderTheSameWard";
import { UnreasonableDive } from "./UnreasonableDive";
import { FightLostUnderEnemyVision } from "./FightLostUnderEnemyVision";
import { MouseClickItemDelivery } from "./MouseClickItemDelivery";
import { MouseClickQuickBuy } from "./MouseClickQuickBuy";
import { NotUnblockedCamp } from "./NotUnblockedCamp";
import {NotPurchasedStick} from "./NotPurchasedStick";
import NotPurchasedItemAgainstHero from "./NotPurchasedItemAgainstHero";

export interface Analysis {
  unusedItems: ReadonlyArray<UnusedItem>;
  unusedAbilities: ReadonlyArray<UnusedAbility>;
  overlappedStuns: ReadonlyArray<OverlappedStun>;
  couriersState: ReadonlyArray<CourierState>;
  notTankedCreepwaves: ReadonlyArray<NotTankedCreepwave>;
  summonGoldFed: ReadonlyArray<SummonGoldFed>;
  midasEfficiency: ReadonlyArray<MidasEfficiency>;
  observersOnVision: ReadonlyArray<ObserverOnVision>;
  smokesOnVision: ReadonlyArray<SmokeOnVision>;
  badFights: ReadonlyArray<BadFight>;
  badSmokeFights: ReadonlyArray<BadSmokeFight>;
  worthlessGlyphs: ReadonlyArray<WorthlessGlyph>;
  lostFightsUnderTheSameWard: ReadonlyArray<LostFightsUnderTheSameWard>;
  fightsLostUnderEnemyVision: ReadonlyArray<FightLostUnderEnemyVision>;
  unreasonableDives: ReadonlyArray<UnreasonableDive>;
  mouseClickItemDeliveries: ReadonlyArray<MouseClickItemDelivery>;
  mouseClickQuickBuys: ReadonlyArray<MouseClickQuickBuy>;
  notUnblockedCamps: ReadonlyArray<NotUnblockedCamp>;
  notPurchasedSticks: ReadonlyArray<NotPurchasedStick>;
  notPurchasedItemAgainstHero: ReadonlyArray<NotPurchasedItemAgainstHero>;
}