// Generated by ScalaTS 0.5.10: https://scala-ts.github.io/scala-ts/

import { Analysis } from './Analysis';
import { MatchInfo } from './MatchInfo';

export interface AnalysisResult {
  matchInfo: MatchInfo;
  analysis: Analysis;
}