// Generated by ScalaTS 0.5.10: https://scala-ts.github.io/scala-ts/

import { Team } from './Team';
import { HeroId } from "./HeroId";

export interface BadFight {
  outnumberedTeam: Team;
  seenHeroes: ReadonlyArray<HeroId>;
  time: string;
}