// Generated by ScalaTS 0.5.10: https://scala-ts.github.io/scala-ts/

import { AbilityDamage } from './AbilityDamage';
import { DamageAmount } from './DamageAmount';
import { HeroId } from './HeroId';
import { ItemDamage } from './ItemDamage';

export interface DamageReceived {
  from: HeroId;
  attackDamage: DamageAmount;
  abilityDamage: ReadonlyArray<AbilityDamage>;
  itemDamage: ReadonlyArray<ItemDamage>;
}
