// Generated by ScalaTS 0.5.10: https://scala-ts.github.io/scala-ts/

import { DamageReceived } from './DamageReceived';
import { GoldEarnings } from './GoldEarnings';
import { HeroId } from './HeroId';

export interface DeathSummary {
  hero: HeroId;
  time: string;
  respawnTime: number;
  damageReceived: ReadonlyArray<DamageReceived>;
  goldPenalty: number;
  goldEarnings: ReadonlyArray<GoldEarnings>;
}
