// Generated by ScalaTS 0.5.10: https://scala-ts.github.io/scala-ts/

import { DamageAmount } from './DamageAmount';
import { ItemId } from './ItemId';

export interface ItemDamage {
  ItemId: ItemId;
  damage: DamageAmount;
}