// Generated by ScalaTS 0.5.10: https://scala-ts.github.io/scala-ts/

export enum Lane {
  Top,
  Middle,
  Bot,
  RadiantJungle,
  DireJungle,
  Roaming
}

export function getLaneName(lane: Lane) {
  switch (lane) {
    case Lane.Top:
    case Lane.Middle:
    case Lane.Bot:
    case Lane.Roaming:
      return Lane[lane]
    case Lane.RadiantJungle:
      return "Radiant Jungle"
    case Lane.DireJungle:
      return "Dire Jungle"
  }
}