// Generated by ScalaTS 0.5.10: https://scala-ts.github.io/scala-ts/

import { HeroId } from './HeroId';

export interface UnusedItem {
  user: HeroId;
  target: HeroId;
  item: string;
  time: string;
}