// Generated by ScalaTS 0.5.10: https://scala-ts.github.io/scala-ts/

import { HeroId } from './HeroId';
import { ItemId } from "./ItemId";

export interface UnusedItem {
  user: HeroId;
  target: HeroId;
  item: ItemId;
  time: string;
}