// Generated by ScalaTS 0.5.10: https://scala-ts.github.io/scala-ts/

import { HeroId } from './HeroId';
import { AbilityId } from "./AbilityId";

export interface UnusedAbility {
  user: HeroId;
  target: HeroId;
  ability: AbilityId;
  time: string;
  withBlink: boolean;
}