// Generated by ScalaTS 0.5.10: https://scala-ts.github.io/scala-ts/

export type AnalysisStatus = 'Processing' | 'Finished' | 'Failed';

export const AnalysisStatusValues = [ 'Processing', 'Finished', 'Failed' ];