// Generated by ScalaTS 0.5.10: https://scala-ts.github.io/scala-ts/

import { BadSmokeFight } from './BadSmokeFight';
import { CourierState } from './CourierState';
import { MidasEfficiency } from './MidasEfficiency';
import { NotTankedCreepwave } from './NotTankedCreepwave';
import { ObserverOnVision } from './ObserverOnVision';
import { OutnumberedFight } from './OutnumberedFight';
import { OverlappedStun } from './OverlappedStun';
import { SmokeOnVision } from './SmokeOnVision';
import { SummonGoldFed } from './SummonGoldFed';
import { UnusedAbility } from './UnusedAbility';
import { UnusedItem } from './UnusedItem';
import { WorthlessGlyph } from './WorthlessGlyph';

export interface Analysis {
  unusedItems: ReadonlyArray<UnusedItem>;
  unusedAbilities: ReadonlyArray<UnusedAbility>;
  overlappedStuns: ReadonlyArray<OverlappedStun>;
  couriersState: ReadonlyArray<CourierState>;
  notTankedCreepwaves: ReadonlyArray<NotTankedCreepwave>;
  summonGoldFed: ReadonlyArray<SummonGoldFed>;
  midasEfficiency: ReadonlyArray<MidasEfficiency>;
  observersOnVision: ReadonlyArray<ObserverOnVision>;
  smokesOnVision: ReadonlyArray<SmokeOnVision>;
  outnumberedFights: ReadonlyArray<OutnumberedFight>;
  badSmokeFights: ReadonlyArray<BadSmokeFight>;
  worthlessGlyphs: ReadonlyArray<WorthlessGlyph>;
}