// Generated by ScalaTS 0.5.10: https://scala-ts.github.io/scala-ts/

import { AnalysisStatus } from './AnalysisStatus';

export interface AnalysisState {
  matchId: number;
  status: AnalysisStatus;
}
