// Generated by ScalaTS 0.5.10: https://scala-ts.github.io/scala-ts/

import { HeroId } from './HeroId';
import { Lane } from './Lane';

export interface NotTankedCreepwave {
  heroes: ReadonlyArray<HeroId>;
  lane: Lane;
  time: string;
}