// Generated by ScalaTS 0.5.10: https://scala-ts.github.io/scala-ts/

export enum Team {
  Radiant,
  Dire
}

export function getOppositeTeam(team: Team) {
  switch (team) {
    case Team.Dire:
      return Team.Radiant;
    case Team.Radiant:
      return Team.Dire;
  }
}