// Generated by ScalaTS 0.5.10: https://scala-ts.github.io/scala-ts/

import { HeroId } from './HeroId';

export interface UnusedAbility {
  user: HeroId;
  target: HeroId;
  ability: string;
  time: string;
  withBlink: boolean;
}